services:
  nginx_web: 
    image: nginx:alpine
    container_name: site
    ports:
      - "81:80"
      - "444:443"
    restart: unless-stopped
    volumes:

      - ./:/usr/share/nginx/html

